enum RestaurantFileCategory {
  RESTAURANT_IMAGE = "RESTAURANT_IMAGE",
  RESTAURANT_LOGO = "RESTAURANT_LOGO",
  RESAURANT_MENU_IMAGE = "RESAURANT_MENU_IMAGE",
  RESTAURANT_GST_CERTIFICATE = "RESTAURANT_GST_CERTIFICATE",
  RESTAURANT_PAN = "RESTAURANT_PAN",
  RESTAURANT_FSSAI_CERTIFICATE = "RESTAURANT_FSSAI_CERTIFICATE",
}

export default RestaurantFileCategory;
