import { BankAccount, PhoneNumber } from "app/types";

export type Restaurant = {
  restaurantId: string;
  restaurantName: string;
  ownerName: string;
  priorityPhoneNumber: PhoneNumber;
  restaurantPhoneNumberPrimary: PhoneNumber;
  restaurantPhoneNumberSecondary: PhoneNumber;
  ownerPhoneNumberPrimary: PhoneNumber;
  ownerPhoneNumberSecondary: PhoneNumber;
  email: string;
  floorId: number;
  averageCostPerPerson: number;
  cuisineStyleIds: number[];
  dishCategoryIds: number[];
  openingTime: string;
  closingTime: string;
  restaurantImageUrl: string;
  restaurantLogoUrl: string;
  menuImageUrl: string;
  gstCertificateUrl: string;
  panFileUrl: string;
  fssaiCertificateUrl: string;
  rating: number;
  numberOfRatings: number;
  restaurantOpen: boolean;
  cuisineTypeId: number;
  bankAccount: BankAccount;
};
